In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('netflix_titles.csv')

In [3]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
import plotly.express as xp

In [6]:
from textblob import TextBlob

In [8]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [12]:
df.shape

(8807, 12)

In [14]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [17]:
x= df.groupby(['rating']).size().reset_index(name='counts')
print(x)

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

In [23]:
chart=xp.pie(x,values='counts',names='rating')
chart.show()

In [35]:
dir=df.groupby(['director']).size().max()
print(dir)

19

In [37]:
df['director']=df['director'].fillna("not specified")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,not specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [38]:
df['cast']=df['cast'].fillna("not specified")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,not specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,not specified,not specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [48]:
director_list=pd.DataFrame()

In [62]:
director_list=df['director'].str.split(',',expand=True).stack()
print(director_list)

0     0    Kirsten Johnson
1     0      not specified
2     0    Julien Leclercq
3     0      not specified
4     0      not specified
                ...
8802  0      David Fincher
8803  0      not specified
8804  0    Ruben Fleischer
8805  0       Peter Hewitt
8806  0        Mozez Singh
Length: 9612, dtype: object

In [63]:
director_list=director_list.to_frame()

In [64]:
print(director_list)

                      0
0    0  Kirsten Johnson
1    0    not specified
2    0  Julien Leclercq
3    0    not specified
4    0    not specified
...                 ...
8802 0    David Fincher
8803 0    not specified
8804 0  Ruben Fleischer
8805 0     Peter Hewitt
8806 0      Mozez Singh

[9612 rows x 1 columns]

In [67]:
director_list.columns=['director']
print(director_list)

               director
0    0  Kirsten Johnson
1    0    not specified
2    0  Julien Leclercq
3    0    not specified
4    0    not specified
...                 ...
8802 0    David Fincher
8803 0    not specified
8804 0  Ruben Fleischer
8805 0     Peter Hewitt
8806 0      Mozez Singh

[9612 rows x 1 columns]

In [72]:
directors=director_list.groupby(['director']).size().reset_index(name='counts')
print(directors)

                       director  counts
0                Aaron Moorhead       2
1                   Aaron Woolf       1
2      Abbas Alibhai Burmawalla       1
3              Abdullah Al Noor       1
4           Abhinav Shiv Tiwari       1
...                         ...     ...
5116                Çagan Irmak       1
5117           Ísold Uggadóttir       1
5118        Óskar Thór Axelsson       1
5119           Ömer Faruk Sorak       2
5120               Şenol Sönmez       2

[5121 rows x 2 columns]

In [ ]:
directors=directors[directors.director !='not specified']

In [80]:
directors=directors.sort_values(by=['counts'],ascending=False)
print(directors)

                  director  counts
5108         not specified    2634
4020         Rajiv Chilaka      22
261              Jan Suter      18
4067           Raúl Campos      18
3235          Marcus Raboy      16
...                    ...     ...
870               Alex Law       1
538            Ravi Jadhav       1
537    Rathindran R Prasad       1
873         Alex Parkinson       1
865           Alex Garland       1

[5121 rows x 2 columns]

In [ ]:
directors.head()